version: 0.0
os: linux
files:
  - source: /
    destination: /myapp
permissions:
  - object: /myapp/startApp.sh
    mode: 777
  - object: /myapp/stopApp.sh
    mode: 777
hooks:
  ApplicationStart:
    - location: startApp.sh
      timeout: 10
  ApplicationStop:
    - location: error.sh
      timeout: 10
